import {
  authMiddleware,
  checkConfirmationCodeMiddleware,
  checkCookieMiddleware,
  checkEmailMiddleware,
  checkEmailPasswordRecoveryMiddleware,
  checkRecoveryPassword,
  createAuthValidationMiddleware,
  inputValidationForCookieMiddleware,
  inputValidationForRegistrationMiddleware,
  registrationAuthValidationMiddleware,
  // authBasicMiddleware,
  authMiddlewareCustomVariant,
  createBlogValidationMiddleware,
  createCommentsValidationMiddleware,
  likeStatusValidationMiddleware,
  createPostForBlogIdValidationMiddleware,
  createPostsValidationMiddleware,
  createUserValidationMiddleware,
} from "./validation";
import { apiConnectMiddleware } from "./api-connects-middleware";
import { inputValidationMiddleware } from "./input-validation.middleware";

export {
  authMiddleware,
  checkConfirmationCodeMiddleware,
  checkCookieMiddleware,
  checkEmailMiddleware,
  checkEmailPasswordRecoveryMiddleware,
  checkRecoveryPassword,
  createAuthValidationMiddleware,
  inputValidationForCookieMiddleware,
  inputValidationForRegistrationMiddleware,
  registrationAuthValidationMiddleware,
  // authBasicMiddleware,
  authMiddlewareCustomVariant,
  createBlogValidationMiddleware,
  createCommentsValidationMiddleware,
  likeStatusValidationMiddleware,
  createPostForBlogIdValidationMiddleware,
  createPostsValidationMiddleware,
  createUserValidationMiddleware,
  apiConnectMiddleware,
  inputValidationMiddleware,
};
